app = "billowing-darkness-4823"
primary_region = "arn"
swap_size_mb = 512

[mounts]
  source = "atticdata"
  destination = "/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[services.concurrency]
  type = "connections"
  hard_limit = 1000
  soft_limit = 1000
