# https://lgug2z.com/articles/deploying-a-cloudflare-r2-backed-nix-binary-cache-attic-on-fly-io/

[database]
url = "sqlite:///data/attic.db?mode=rwc"

[storage]
bucket = "attic"
type = "s3"
region = "auto"
endpoint = "https://dc1a5e335b41ced4dcd0a7a15b2808f1.r2.cloudflarestorage.com"

[chunking]
nar-size-threshold = 65536
min-size = 16384
avg-size = 65536
max-size = 262144

[compression]
type = "zstd"

[garbage-collection]
interval = "12 hours"
