#!/bin/bash

# Only run when cloning
if [[ -n "${1//0}" ]]; then
    exit
fi

# TODO: check old commits to see if the user is correct
# TODO: warn if no matching git config applies
# TODO: maybe disable pushing: git remote set-url --push origin no_push
# TODO: make sure normal hooks are executed too: https://stackoverflow.com/a/71939092

echo POST CLONE
echo
echo Username:
git config user.name
echo Email:
git config user.email
